// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: internal/proto/gophkeeper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ------------------------------------
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type PingRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 PingRequest_builder) Build() *PingRequest {
	m0 := &PingRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type PingResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Message string                 `protobuf:"bytes,1,opt,name=message,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.xxx_hidden_Message
	}
	return ""
}

func (x *PingResponse) SetMessage(v string) {
	x.xxx_hidden_Message = v
}

type PingResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Message string
}

func (b0 PingResponse_builder) Build() *PingResponse {
	m0 := &PingResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Message = b.Message
	return m0
}

// ------------------------------------
type Token struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_UserId int64                  `protobuf:"varint,1,opt,name=userId,proto3"`
	xxx_hidden_Token  string                 `protobuf:"bytes,2,opt,name=token,proto3"`
	xxx_hidden_Iat    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=iat,proto3"`
	xxx_hidden_Exp    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=exp,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Token) GetUserId() int64 {
	if x != nil {
		return x.xxx_hidden_UserId
	}
	return 0
}

func (x *Token) GetToken() string {
	if x != nil {
		return x.xxx_hidden_Token
	}
	return ""
}

func (x *Token) GetIat() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Iat
	}
	return nil
}

func (x *Token) GetExp() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Exp
	}
	return nil
}

func (x *Token) SetUserId(v int64) {
	x.xxx_hidden_UserId = v
}

func (x *Token) SetToken(v string) {
	x.xxx_hidden_Token = v
}

func (x *Token) SetIat(v *timestamppb.Timestamp) {
	x.xxx_hidden_Iat = v
}

func (x *Token) SetExp(v *timestamppb.Timestamp) {
	x.xxx_hidden_Exp = v
}

func (x *Token) HasIat() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Iat != nil
}

func (x *Token) HasExp() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Exp != nil
}

func (x *Token) ClearIat() {
	x.xxx_hidden_Iat = nil
}

func (x *Token) ClearExp() {
	x.xxx_hidden_Exp = nil
}

type Token_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	UserId int64
	Token  string
	Iat    *timestamppb.Timestamp
	Exp    *timestamppb.Timestamp
}

func (b0 Token_builder) Build() *Token {
	m0 := &Token{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_UserId = b.UserId
	x.xxx_hidden_Token = b.Token
	x.xxx_hidden_Iat = b.Iat
	x.xxx_hidden_Exp = b.Exp
	return m0
}

// ------------------------------------
type User struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_UserId    int64                  `protobuf:"varint,1,opt,name=userId,proto3"`
	xxx_hidden_Username  string                 `protobuf:"bytes,2,opt,name=username,proto3"`
	xxx_hidden_CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=createdAt,proto3"`
	xxx_hidden_UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updatedAt,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *User) GetUserId() int64 {
	if x != nil {
		return x.xxx_hidden_UserId
	}
	return 0
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.xxx_hidden_Username
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return nil
}

func (x *User) SetUserId(v int64) {
	x.xxx_hidden_UserId = v
}

func (x *User) SetUsername(v string) {
	x.xxx_hidden_Username = v
}

func (x *User) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *User) SetUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdatedAt = v
}

func (x *User) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *User) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedAt != nil
}

func (x *User) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *User) ClearUpdatedAt() {
	x.xxx_hidden_UpdatedAt = nil
}

type User_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	UserId    int64
	Username  string
	CreatedAt *timestamppb.Timestamp
	UpdatedAt *timestamppb.Timestamp
}

func (b0 User_builder) Build() *User {
	m0 := &User{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_UserId = b.UserId
	x.xxx_hidden_Username = b.Username
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	return m0
}

type AuthenticationRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Username string                 `protobuf:"bytes,1,opt,name=username,proto3"`
	xxx_hidden_Password string                 `protobuf:"bytes,2,opt,name=password,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AuthenticationRequest) Reset() {
	*x = AuthenticationRequest{}
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationRequest) ProtoMessage() {}

func (x *AuthenticationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthenticationRequest) GetUsername() string {
	if x != nil {
		return x.xxx_hidden_Username
	}
	return ""
}

func (x *AuthenticationRequest) GetPassword() string {
	if x != nil {
		return x.xxx_hidden_Password
	}
	return ""
}

func (x *AuthenticationRequest) SetUsername(v string) {
	x.xxx_hidden_Username = v
}

func (x *AuthenticationRequest) SetPassword(v string) {
	x.xxx_hidden_Password = v
}

type AuthenticationRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Username string
	Password string
}

func (b0 AuthenticationRequest_builder) Build() *AuthenticationRequest {
	m0 := &AuthenticationRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Username = b.Username
	x.xxx_hidden_Password = b.Password
	return m0
}

type AuthenticationResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_AccessToken *Token                 `protobuf:"bytes,1,opt,name=accessToken,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AuthenticationResponse) Reset() {
	*x = AuthenticationResponse{}
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationResponse) ProtoMessage() {}

func (x *AuthenticationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthenticationResponse) GetAccessToken() *Token {
	if x != nil {
		return x.xxx_hidden_AccessToken
	}
	return nil
}

func (x *AuthenticationResponse) SetAccessToken(v *Token) {
	x.xxx_hidden_AccessToken = v
}

func (x *AuthenticationResponse) HasAccessToken() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_AccessToken != nil
}

func (x *AuthenticationResponse) ClearAccessToken() {
	x.xxx_hidden_AccessToken = nil
}

type AuthenticationResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	AccessToken *Token
}

func (b0 AuthenticationResponse_builder) Build() *AuthenticationResponse {
	m0 := &AuthenticationResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_AccessToken = b.AccessToken
	return m0
}

type RegistrationRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Username string                 `protobuf:"bytes,1,opt,name=username,proto3"`
	xxx_hidden_Password string                 `protobuf:"bytes,2,opt,name=password,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RegistrationRequest) Reset() {
	*x = RegistrationRequest{}
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationRequest) ProtoMessage() {}

func (x *RegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegistrationRequest) GetUsername() string {
	if x != nil {
		return x.xxx_hidden_Username
	}
	return ""
}

func (x *RegistrationRequest) GetPassword() string {
	if x != nil {
		return x.xxx_hidden_Password
	}
	return ""
}

func (x *RegistrationRequest) SetUsername(v string) {
	x.xxx_hidden_Username = v
}

func (x *RegistrationRequest) SetPassword(v string) {
	x.xxx_hidden_Password = v
}

type RegistrationRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Username string
	Password string
}

func (b0 RegistrationRequest_builder) Build() *RegistrationRequest {
	m0 := &RegistrationRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Username = b.Username
	x.xxx_hidden_Password = b.Password
	return m0
}

type RegistrationResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_AccessToken *Token                 `protobuf:"bytes,1,opt,name=accessToken,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RegistrationResponse) Reset() {
	*x = RegistrationResponse{}
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationResponse) ProtoMessage() {}

func (x *RegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegistrationResponse) GetAccessToken() *Token {
	if x != nil {
		return x.xxx_hidden_AccessToken
	}
	return nil
}

func (x *RegistrationResponse) SetAccessToken(v *Token) {
	x.xxx_hidden_AccessToken = v
}

func (x *RegistrationResponse) HasAccessToken() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_AccessToken != nil
}

func (x *RegistrationResponse) ClearAccessToken() {
	x.xxx_hidden_AccessToken = nil
}

type RegistrationResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	AccessToken *Token
}

func (b0 RegistrationResponse_builder) Build() *RegistrationResponse {
	m0 := &RegistrationResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_AccessToken = b.AccessToken
	return m0
}

type UserExistRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Username string                 `protobuf:"bytes,1,opt,name=username,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UserExistRequest) Reset() {
	*x = UserExistRequest{}
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserExistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserExistRequest) ProtoMessage() {}

func (x *UserExistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserExistRequest) GetUsername() string {
	if x != nil {
		return x.xxx_hidden_Username
	}
	return ""
}

func (x *UserExistRequest) SetUsername(v string) {
	x.xxx_hidden_Username = v
}

type UserExistRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Username string
}

func (b0 UserExistRequest_builder) Build() *UserExistRequest {
	m0 := &UserExistRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Username = b.Username
	return m0
}

type UserExistResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Exist bool                   `protobuf:"varint,1,opt,name=exist,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserExistResponse) Reset() {
	*x = UserExistResponse{}
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserExistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserExistResponse) ProtoMessage() {}

func (x *UserExistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserExistResponse) GetExist() bool {
	if x != nil {
		return x.xxx_hidden_Exist
	}
	return false
}

func (x *UserExistResponse) SetExist(v bool) {
	x.xxx_hidden_Exist = v
}

type UserExistResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Exist bool
}

func (b0 UserExistResponse_builder) Build() *UserExistResponse {
	m0 := &UserExistResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Exist = b.Exist
	return m0
}

// ------------------------------------
type Binary struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id        int64                  `protobuf:"varint,1,opt,name=id,proto3"`
	xxx_hidden_UserId    int64                  `protobuf:"varint,2,opt,name=userId,proto3"`
	xxx_hidden_Name      string                 `protobuf:"bytes,3,opt,name=name,proto3"`
	xxx_hidden_CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=createdAt,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Binary) Reset() {
	*x = Binary{}
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Binary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Binary) ProtoMessage() {}

func (x *Binary) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Binary) GetId() int64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *Binary) GetUserId() int64 {
	if x != nil {
		return x.xxx_hidden_UserId
	}
	return 0
}

func (x *Binary) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Binary) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *Binary) SetId(v int64) {
	x.xxx_hidden_Id = v
}

func (x *Binary) SetUserId(v int64) {
	x.xxx_hidden_UserId = v
}

func (x *Binary) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *Binary) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *Binary) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *Binary) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

type Binary_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id        int64
	UserId    int64
	Name      string
	CreatedAt *timestamppb.Timestamp
}

func (b0 Binary_builder) Build() *Binary {
	m0 := &Binary{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_UserId = b.UserId
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_CreatedAt = b.CreatedAt
	return m0
}

type UploadBinaryRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_Data        []byte                 `protobuf:"bytes,2,opt,name=data,proto3"`
	xxx_hidden_AccessToken *Token                 `protobuf:"bytes,3,opt,name=accessToken,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UploadBinaryRequest) Reset() {
	*x = UploadBinaryRequest{}
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadBinaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadBinaryRequest) ProtoMessage() {}

func (x *UploadBinaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UploadBinaryRequest) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *UploadBinaryRequest) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *UploadBinaryRequest) GetAccessToken() *Token {
	if x != nil {
		return x.xxx_hidden_AccessToken
	}
	return nil
}

func (x *UploadBinaryRequest) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *UploadBinaryRequest) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
}

func (x *UploadBinaryRequest) SetAccessToken(v *Token) {
	x.xxx_hidden_AccessToken = v
}

func (x *UploadBinaryRequest) HasAccessToken() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_AccessToken != nil
}

func (x *UploadBinaryRequest) ClearAccessToken() {
	x.xxx_hidden_AccessToken = nil
}

type UploadBinaryRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name        string
	Data        []byte
	AccessToken *Token
}

func (b0 UploadBinaryRequest_builder) Build() *UploadBinaryRequest {
	m0 := &UploadBinaryRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Data = b.Data
	x.xxx_hidden_AccessToken = b.AccessToken
	return m0
}

type UploadBinaryResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UploadBinaryResponse) Reset() {
	*x = UploadBinaryResponse{}
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadBinaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadBinaryResponse) ProtoMessage() {}

func (x *UploadBinaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UploadBinaryResponse) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *UploadBinaryResponse) SetName(v string) {
	x.xxx_hidden_Name = v
}

type UploadBinaryResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name string
}

func (b0 UploadBinaryResponse_builder) Build() *UploadBinaryResponse {
	m0 := &UploadBinaryResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	return m0
}

type GetNodeBinaryRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_AccessToken *Token                 `protobuf:"bytes,2,opt,name=accessToken,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetNodeBinaryRequest) Reset() {
	*x = GetNodeBinaryRequest{}
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeBinaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeBinaryRequest) ProtoMessage() {}

func (x *GetNodeBinaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetNodeBinaryRequest) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *GetNodeBinaryRequest) GetAccessToken() *Token {
	if x != nil {
		return x.xxx_hidden_AccessToken
	}
	return nil
}

func (x *GetNodeBinaryRequest) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *GetNodeBinaryRequest) SetAccessToken(v *Token) {
	x.xxx_hidden_AccessToken = v
}

func (x *GetNodeBinaryRequest) HasAccessToken() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_AccessToken != nil
}

func (x *GetNodeBinaryRequest) ClearAccessToken() {
	x.xxx_hidden_AccessToken = nil
}

type GetNodeBinaryRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name        string
	AccessToken *Token
}

func (b0 GetNodeBinaryRequest_builder) Build() *GetNodeBinaryRequest {
	m0 := &GetNodeBinaryRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_AccessToken = b.AccessToken
	return m0
}

type GetNodeBinaryResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Data *Binary                `protobuf:"bytes,1,opt,name=data,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetNodeBinaryResponse) Reset() {
	*x = GetNodeBinaryResponse{}
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeBinaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeBinaryResponse) ProtoMessage() {}

func (x *GetNodeBinaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetNodeBinaryResponse) GetData() *Binary {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *GetNodeBinaryResponse) SetData(v *Binary) {
	x.xxx_hidden_Data = v
}

func (x *GetNodeBinaryResponse) HasData() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Data != nil
}

func (x *GetNodeBinaryResponse) ClearData() {
	x.xxx_hidden_Data = nil
}

type GetNodeBinaryResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Data *Binary
}

func (b0 GetNodeBinaryResponse_builder) Build() *GetNodeBinaryResponse {
	m0 := &GetNodeBinaryResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Data = b.Data
	return m0
}

type GetListBinaryRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_AccessToken *Token                 `protobuf:"bytes,1,opt,name=accessToken,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetListBinaryRequest) Reset() {
	*x = GetListBinaryRequest{}
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListBinaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListBinaryRequest) ProtoMessage() {}

func (x *GetListBinaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetListBinaryRequest) GetAccessToken() *Token {
	if x != nil {
		return x.xxx_hidden_AccessToken
	}
	return nil
}

func (x *GetListBinaryRequest) SetAccessToken(v *Token) {
	x.xxx_hidden_AccessToken = v
}

func (x *GetListBinaryRequest) HasAccessToken() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_AccessToken != nil
}

func (x *GetListBinaryRequest) ClearAccessToken() {
	x.xxx_hidden_AccessToken = nil
}

type GetListBinaryRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	AccessToken *Token
}

func (b0 GetListBinaryRequest_builder) Build() *GetListBinaryRequest {
	m0 := &GetListBinaryRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_AccessToken = b.AccessToken
	return m0
}

type GetListBinaryResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Node *[]*Binary             `protobuf:"bytes,1,rep,name=node,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetListBinaryResponse) Reset() {
	*x = GetListBinaryResponse{}
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListBinaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListBinaryResponse) ProtoMessage() {}

func (x *GetListBinaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetListBinaryResponse) GetNode() []*Binary {
	if x != nil {
		if x.xxx_hidden_Node != nil {
			return *x.xxx_hidden_Node
		}
	}
	return nil
}

func (x *GetListBinaryResponse) SetNode(v []*Binary) {
	x.xxx_hidden_Node = &v
}

type GetListBinaryResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Node []*Binary
}

func (b0 GetListBinaryResponse_builder) Build() *GetListBinaryResponse {
	m0 := &GetListBinaryResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Node = &b.Node
	return m0
}

type DeleteBinaryRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_AccessToken *Token                 `protobuf:"bytes,2,opt,name=accessToken,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DeleteBinaryRequest) Reset() {
	*x = DeleteBinaryRequest{}
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBinaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBinaryRequest) ProtoMessage() {}

func (x *DeleteBinaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteBinaryRequest) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *DeleteBinaryRequest) GetAccessToken() *Token {
	if x != nil {
		return x.xxx_hidden_AccessToken
	}
	return nil
}

func (x *DeleteBinaryRequest) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *DeleteBinaryRequest) SetAccessToken(v *Token) {
	x.xxx_hidden_AccessToken = v
}

func (x *DeleteBinaryRequest) HasAccessToken() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_AccessToken != nil
}

func (x *DeleteBinaryRequest) ClearAccessToken() {
	x.xxx_hidden_AccessToken = nil
}

type DeleteBinaryRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name        string
	AccessToken *Token
}

func (b0 DeleteBinaryRequest_builder) Build() *DeleteBinaryRequest {
	m0 := &DeleteBinaryRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_AccessToken = b.AccessToken
	return m0
}

type DeleteBinaryResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id int64                  `protobuf:"varint,1,opt,name=id,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBinaryResponse) Reset() {
	*x = DeleteBinaryResponse{}
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBinaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBinaryResponse) ProtoMessage() {}

func (x *DeleteBinaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteBinaryResponse) GetId() int64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *DeleteBinaryResponse) SetId(v int64) {
	x.xxx_hidden_Id = v
}

type DeleteBinaryResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id int64
}

func (b0 DeleteBinaryResponse_builder) Build() *DeleteBinaryResponse {
	m0 := &DeleteBinaryResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	return m0
}

type DownloadBinaryRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_AccessToken *Token                 `protobuf:"bytes,3,opt,name=accessToken,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DownloadBinaryRequest) Reset() {
	*x = DownloadBinaryRequest{}
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadBinaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadBinaryRequest) ProtoMessage() {}

func (x *DownloadBinaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DownloadBinaryRequest) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *DownloadBinaryRequest) GetAccessToken() *Token {
	if x != nil {
		return x.xxx_hidden_AccessToken
	}
	return nil
}

func (x *DownloadBinaryRequest) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *DownloadBinaryRequest) SetAccessToken(v *Token) {
	x.xxx_hidden_AccessToken = v
}

func (x *DownloadBinaryRequest) HasAccessToken() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_AccessToken != nil
}

func (x *DownloadBinaryRequest) ClearAccessToken() {
	x.xxx_hidden_AccessToken = nil
}

type DownloadBinaryRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name        string
	AccessToken *Token
}

func (b0 DownloadBinaryRequest_builder) Build() *DownloadBinaryRequest {
	m0 := &DownloadBinaryRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_AccessToken = b.AccessToken
	return m0
}

type DownloadBinaryResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id   int64                  `protobuf:"varint,1,opt,name=id,proto3"`
	xxx_hidden_Data []byte                 `protobuf:"bytes,2,opt,name=data,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DownloadBinaryResponse) Reset() {
	*x = DownloadBinaryResponse{}
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadBinaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadBinaryResponse) ProtoMessage() {}

func (x *DownloadBinaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DownloadBinaryResponse) GetId() int64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *DownloadBinaryResponse) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *DownloadBinaryResponse) SetId(v int64) {
	x.xxx_hidden_Id = v
}

func (x *DownloadBinaryResponse) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
}

type DownloadBinaryResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id   int64
	Data []byte
}

func (b0 DownloadBinaryResponse_builder) Build() *DownloadBinaryResponse {
	m0 := &DownloadBinaryResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Data = b.Data
	return m0
}

// ------------------------------------
type Entity struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id        int64                  `protobuf:"varint,1,opt,name=id,proto3"`
	xxx_hidden_UserId    int64                  `protobuf:"varint,2,opt,name=userId,proto3"`
	xxx_hidden_Data      []byte                 `protobuf:"bytes,3,opt,name=data,proto3"`
	xxx_hidden_Metadata  string                 `protobuf:"bytes,4,opt,name=metadata,proto3"`
	xxx_hidden_CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=createdAt,proto3"`
	xxx_hidden_UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updatedAt,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Entity) GetId() int64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *Entity) GetUserId() int64 {
	if x != nil {
		return x.xxx_hidden_UserId
	}
	return 0
}

func (x *Entity) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *Entity) GetMetadata() string {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return ""
}

func (x *Entity) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *Entity) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return nil
}

func (x *Entity) SetId(v int64) {
	x.xxx_hidden_Id = v
}

func (x *Entity) SetUserId(v int64) {
	x.xxx_hidden_UserId = v
}

func (x *Entity) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
}

func (x *Entity) SetMetadata(v string) {
	x.xxx_hidden_Metadata = v
}

func (x *Entity) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *Entity) SetUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdatedAt = v
}

func (x *Entity) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *Entity) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedAt != nil
}

func (x *Entity) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *Entity) ClearUpdatedAt() {
	x.xxx_hidden_UpdatedAt = nil
}

type Entity_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id        int64
	UserId    int64
	Data      []byte
	Metadata  string
	CreatedAt *timestamppb.Timestamp
	UpdatedAt *timestamppb.Timestamp
}

func (b0 Entity_builder) Build() *Entity {
	m0 := &Entity{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_UserId = b.UserId
	x.xxx_hidden_Data = b.Data
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	return m0
}

type CreateEntityRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Data        []byte                 `protobuf:"bytes,1,opt,name=data,proto3"`
	xxx_hidden_Metadata    string                 `protobuf:"bytes,2,opt,name=metadata,proto3"`
	xxx_hidden_AccessToken *Token                 `protobuf:"bytes,3,opt,name=accessToken,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateEntityRequest) Reset() {
	*x = CreateEntityRequest{}
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEntityRequest) ProtoMessage() {}

func (x *CreateEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateEntityRequest) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *CreateEntityRequest) GetMetadata() string {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return ""
}

func (x *CreateEntityRequest) GetAccessToken() *Token {
	if x != nil {
		return x.xxx_hidden_AccessToken
	}
	return nil
}

func (x *CreateEntityRequest) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
}

func (x *CreateEntityRequest) SetMetadata(v string) {
	x.xxx_hidden_Metadata = v
}

func (x *CreateEntityRequest) SetAccessToken(v *Token) {
	x.xxx_hidden_AccessToken = v
}

func (x *CreateEntityRequest) HasAccessToken() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_AccessToken != nil
}

func (x *CreateEntityRequest) ClearAccessToken() {
	x.xxx_hidden_AccessToken = nil
}

type CreateEntityRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Data        []byte
	Metadata    string
	AccessToken *Token
}

func (b0 CreateEntityRequest_builder) Build() *CreateEntityRequest {
	m0 := &CreateEntityRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Data = b.Data
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_AccessToken = b.AccessToken
	return m0
}

type CreateEntityResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id int64                  `protobuf:"varint,1,opt,name=id,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEntityResponse) Reset() {
	*x = CreateEntityResponse{}
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEntityResponse) ProtoMessage() {}

func (x *CreateEntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateEntityResponse) GetId() int64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *CreateEntityResponse) SetId(v int64) {
	x.xxx_hidden_Id = v
}

type CreateEntityResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id int64
}

func (b0 CreateEntityResponse_builder) Build() *CreateEntityResponse {
	m0 := &CreateEntityResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	return m0
}

type GetListEntityRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type        string                 `protobuf:"bytes,1,opt,name=type,proto3"`
	xxx_hidden_AccessToken *Token                 `protobuf:"bytes,2,opt,name=accessToken,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetListEntityRequest) Reset() {
	*x = GetListEntityRequest{}
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListEntityRequest) ProtoMessage() {}

func (x *GetListEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetListEntityRequest) GetType() string {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return ""
}

func (x *GetListEntityRequest) GetAccessToken() *Token {
	if x != nil {
		return x.xxx_hidden_AccessToken
	}
	return nil
}

func (x *GetListEntityRequest) SetType(v string) {
	x.xxx_hidden_Type = v
}

func (x *GetListEntityRequest) SetAccessToken(v *Token) {
	x.xxx_hidden_AccessToken = v
}

func (x *GetListEntityRequest) HasAccessToken() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_AccessToken != nil
}

func (x *GetListEntityRequest) ClearAccessToken() {
	x.xxx_hidden_AccessToken = nil
}

type GetListEntityRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Type        string
	AccessToken *Token
}

func (b0 GetListEntityRequest_builder) Build() *GetListEntityRequest {
	m0 := &GetListEntityRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_AccessToken = b.AccessToken
	return m0
}

type GetListEntityResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Node *[]*Entity             `protobuf:"bytes,1,rep,name=node,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetListEntityResponse) Reset() {
	*x = GetListEntityResponse{}
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListEntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListEntityResponse) ProtoMessage() {}

func (x *GetListEntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetListEntityResponse) GetNode() []*Entity {
	if x != nil {
		if x.xxx_hidden_Node != nil {
			return *x.xxx_hidden_Node
		}
	}
	return nil
}

func (x *GetListEntityResponse) SetNode(v []*Entity) {
	x.xxx_hidden_Node = &v
}

type GetListEntityResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Node []*Entity
}

func (b0 GetListEntityResponse_builder) Build() *GetListEntityResponse {
	m0 := &GetListEntityResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Node = &b.Node
	return m0
}

type DeleteEntityRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_Type        string                 `protobuf:"bytes,2,opt,name=type,proto3"`
	xxx_hidden_AccessToken *Token                 `protobuf:"bytes,3,opt,name=accessToken,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DeleteEntityRequest) Reset() {
	*x = DeleteEntityRequest{}
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEntityRequest) ProtoMessage() {}

func (x *DeleteEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteEntityRequest) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *DeleteEntityRequest) GetType() string {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return ""
}

func (x *DeleteEntityRequest) GetAccessToken() *Token {
	if x != nil {
		return x.xxx_hidden_AccessToken
	}
	return nil
}

func (x *DeleteEntityRequest) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *DeleteEntityRequest) SetType(v string) {
	x.xxx_hidden_Type = v
}

func (x *DeleteEntityRequest) SetAccessToken(v *Token) {
	x.xxx_hidden_AccessToken = v
}

func (x *DeleteEntityRequest) HasAccessToken() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_AccessToken != nil
}

func (x *DeleteEntityRequest) ClearAccessToken() {
	x.xxx_hidden_AccessToken = nil
}

type DeleteEntityRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name        string
	Type        string
	AccessToken *Token
}

func (b0 DeleteEntityRequest_builder) Build() *DeleteEntityRequest {
	m0 := &DeleteEntityRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_AccessToken = b.AccessToken
	return m0
}

type DeleteEntityResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id int64                  `protobuf:"varint,1,opt,name=id,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEntityResponse) Reset() {
	*x = DeleteEntityResponse{}
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEntityResponse) ProtoMessage() {}

func (x *DeleteEntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteEntityResponse) GetId() int64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *DeleteEntityResponse) SetId(v int64) {
	x.xxx_hidden_Id = v
}

type DeleteEntityResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id int64
}

func (b0 DeleteEntityResponse_builder) Build() *DeleteEntityResponse {
	m0 := &DeleteEntityResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	return m0
}

type UpdateEntityRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_Type        string                 `protobuf:"bytes,2,opt,name=type,proto3"`
	xxx_hidden_Data        []byte                 `protobuf:"bytes,3,opt,name=data,proto3"`
	xxx_hidden_AccessToken *Token                 `protobuf:"bytes,4,opt,name=accessToken,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UpdateEntityRequest) Reset() {
	*x = UpdateEntityRequest{}
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEntityRequest) ProtoMessage() {}

func (x *UpdateEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateEntityRequest) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *UpdateEntityRequest) GetType() string {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return ""
}

func (x *UpdateEntityRequest) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *UpdateEntityRequest) GetAccessToken() *Token {
	if x != nil {
		return x.xxx_hidden_AccessToken
	}
	return nil
}

func (x *UpdateEntityRequest) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *UpdateEntityRequest) SetType(v string) {
	x.xxx_hidden_Type = v
}

func (x *UpdateEntityRequest) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
}

func (x *UpdateEntityRequest) SetAccessToken(v *Token) {
	x.xxx_hidden_AccessToken = v
}

func (x *UpdateEntityRequest) HasAccessToken() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_AccessToken != nil
}

func (x *UpdateEntityRequest) ClearAccessToken() {
	x.xxx_hidden_AccessToken = nil
}

type UpdateEntityRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name        string
	Type        string
	Data        []byte
	AccessToken *Token
}

func (b0 UpdateEntityRequest_builder) Build() *UpdateEntityRequest {
	m0 := &UpdateEntityRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_Data = b.Data
	x.xxx_hidden_AccessToken = b.AccessToken
	return m0
}

type UpdateEntityResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id int64                  `protobuf:"varint,1,opt,name=id,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEntityResponse) Reset() {
	*x = UpdateEntityResponse{}
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEntityResponse) ProtoMessage() {}

func (x *UpdateEntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gophkeeper_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateEntityResponse) GetId() int64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *UpdateEntityResponse) SetId(v int64) {
	x.xxx_hidden_Id = v
}

type UpdateEntityResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id int64
}

func (b0 UpdateEntityResponse_builder) Build() *UpdateEntityResponse {
	m0 := &UpdateEntityResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	return m0
}

var File_internal_proto_gophkeeper_proto protoreflect.FileDescriptor

const file_internal_proto_gophkeeper_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/proto/gophkeeper.proto\x12\x06keeper\x1a\x1fgoogle/protobuf/timestamp.proto\"\r\n" +
	"\vPingRequest\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x91\x01\n" +
	"\x05Token\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12,\n" +
	"\x03iat\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x03iat\x12,\n" +
	"\x03exp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x03exp\"\xae\x01\n" +
	"\x04User\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x128\n" +
	"\tcreatedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"O\n" +
	"\x15AuthenticationRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"I\n" +
	"\x16AuthenticationResponse\x12/\n" +
	"\vaccessToken\x18\x01 \x01(\v2\r.keeper.TokenR\vaccessToken\"M\n" +
	"\x13RegistrationRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"G\n" +
	"\x14RegistrationResponse\x12/\n" +
	"\vaccessToken\x18\x01 \x01(\v2\r.keeper.TokenR\vaccessToken\".\n" +
	"\x10UserExistRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\")\n" +
	"\x11UserExistResponse\x12\x14\n" +
	"\x05exist\x18\x01 \x01(\bR\x05exist\"~\n" +
	"\x06Binary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x128\n" +
	"\tcreatedAt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"n\n" +
	"\x13UploadBinaryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12/\n" +
	"\vaccessToken\x18\x03 \x01(\v2\r.keeper.TokenR\vaccessToken\"*\n" +
	"\x14UploadBinaryResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"[\n" +
	"\x14GetNodeBinaryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12/\n" +
	"\vaccessToken\x18\x02 \x01(\v2\r.keeper.TokenR\vaccessToken\";\n" +
	"\x15GetNodeBinaryResponse\x12\"\n" +
	"\x04data\x18\x01 \x01(\v2\x0e.keeper.BinaryR\x04data\"G\n" +
	"\x14GetListBinaryRequest\x12/\n" +
	"\vaccessToken\x18\x01 \x01(\v2\r.keeper.TokenR\vaccessToken\";\n" +
	"\x15GetListBinaryResponse\x12\"\n" +
	"\x04node\x18\x01 \x03(\v2\x0e.keeper.BinaryR\x04node\"Z\n" +
	"\x13DeleteBinaryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12/\n" +
	"\vaccessToken\x18\x02 \x01(\v2\r.keeper.TokenR\vaccessToken\"&\n" +
	"\x14DeleteBinaryResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\\\n" +
	"\x15DownloadBinaryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12/\n" +
	"\vaccessToken\x18\x03 \x01(\v2\r.keeper.TokenR\vaccessToken\"<\n" +
	"\x16DownloadBinaryResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\xd4\x01\n" +
	"\x06Entity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\tR\bmetadata\x128\n" +
	"\tcreatedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"v\n" +
	"\x13CreateEntityRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1a\n" +
	"\bmetadata\x18\x02 \x01(\tR\bmetadata\x12/\n" +
	"\vaccessToken\x18\x03 \x01(\v2\r.keeper.TokenR\vaccessToken\"&\n" +
	"\x14CreateEntityResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"[\n" +
	"\x14GetListEntityRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12/\n" +
	"\vaccessToken\x18\x02 \x01(\v2\r.keeper.TokenR\vaccessToken\";\n" +
	"\x15GetListEntityResponse\x12\"\n" +
	"\x04node\x18\x01 \x03(\v2\x0e.keeper.EntityR\x04node\"n\n" +
	"\x13DeleteEntityRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12/\n" +
	"\vaccessToken\x18\x03 \x01(\v2\r.keeper.TokenR\vaccessToken\"&\n" +
	"\x14DeleteEntityResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x82\x01\n" +
	"\x13UpdateEntityRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12/\n" +
	"\vaccessToken\x18\x04 \x01(\v2\r.keeper.TokenR\vaccessToken\"&\n" +
	"\x14UpdateEntityResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id2\xf9\x06\n" +
	"\n" +
	"GophKeeper\x121\n" +
	"\x04Ping\x12\x13.keeper.PingRequest\x1a\x14.keeper.PingResponse\x12@\n" +
	"\tUserExist\x12\x18.keeper.UserExistRequest\x1a\x19.keeper.UserExistResponse\x12O\n" +
	"\x0eAuthentication\x12\x1d.keeper.AuthenticationRequest\x1a\x1e.keeper.AuthenticationResponse\x12I\n" +
	"\fRegistration\x12\x1b.keeper.RegistrationRequest\x1a\x1c.keeper.RegistrationResponse\x12G\n" +
	"\n" +
	"FileUpload\x12\x1b.keeper.UploadBinaryRequest\x1a\x1c.keeper.UploadBinaryResponse\x12J\n" +
	"\vFileGetList\x12\x1c.keeper.GetListBinaryRequest\x1a\x1d.keeper.GetListBinaryResponse\x12G\n" +
	"\n" +
	"FileRemove\x12\x1b.keeper.DeleteBinaryRequest\x1a\x1c.keeper.DeleteBinaryResponse\x12M\n" +
	"\fFileDownload\x12\x1d.keeper.DownloadBinaryRequest\x1a\x1e.keeper.DownloadBinaryResponse\x12I\n" +
	"\fEntityCreate\x12\x1b.keeper.CreateEntityRequest\x1a\x1c.keeper.CreateEntityResponse\x12L\n" +
	"\rEntityGetList\x12\x1c.keeper.GetListEntityRequest\x1a\x1d.keeper.GetListEntityResponse\x12I\n" +
	"\fEntityDelete\x12\x1b.keeper.DeleteEntityRequest\x1a\x1c.keeper.DeleteEntityResponse\x12I\n" +
	"\fEntityUpdate\x12\x1b.keeper.UpdateEntityRequest\x1a\x1c.keeper.UpdateEntityResponseBFZDgithub.com/serg1732/practicum-second-coursework/internal/proto;protob\x06proto3"

var file_internal_proto_gophkeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_internal_proto_gophkeeper_proto_goTypes = []any{
	(*PingRequest)(nil),            // 0: keeper.PingRequest
	(*PingResponse)(nil),           // 1: keeper.PingResponse
	(*Token)(nil),                  // 2: keeper.Token
	(*User)(nil),                   // 3: keeper.User
	(*AuthenticationRequest)(nil),  // 4: keeper.AuthenticationRequest
	(*AuthenticationResponse)(nil), // 5: keeper.AuthenticationResponse
	(*RegistrationRequest)(nil),    // 6: keeper.RegistrationRequest
	(*RegistrationResponse)(nil),   // 7: keeper.RegistrationResponse
	(*UserExistRequest)(nil),       // 8: keeper.UserExistRequest
	(*UserExistResponse)(nil),      // 9: keeper.UserExistResponse
	(*Binary)(nil),                 // 10: keeper.Binary
	(*UploadBinaryRequest)(nil),    // 11: keeper.UploadBinaryRequest
	(*UploadBinaryResponse)(nil),   // 12: keeper.UploadBinaryResponse
	(*GetNodeBinaryRequest)(nil),   // 13: keeper.GetNodeBinaryRequest
	(*GetNodeBinaryResponse)(nil),  // 14: keeper.GetNodeBinaryResponse
	(*GetListBinaryRequest)(nil),   // 15: keeper.GetListBinaryRequest
	(*GetListBinaryResponse)(nil),  // 16: keeper.GetListBinaryResponse
	(*DeleteBinaryRequest)(nil),    // 17: keeper.DeleteBinaryRequest
	(*DeleteBinaryResponse)(nil),   // 18: keeper.DeleteBinaryResponse
	(*DownloadBinaryRequest)(nil),  // 19: keeper.DownloadBinaryRequest
	(*DownloadBinaryResponse)(nil), // 20: keeper.DownloadBinaryResponse
	(*Entity)(nil),                 // 21: keeper.Entity
	(*CreateEntityRequest)(nil),    // 22: keeper.CreateEntityRequest
	(*CreateEntityResponse)(nil),   // 23: keeper.CreateEntityResponse
	(*GetListEntityRequest)(nil),   // 24: keeper.GetListEntityRequest
	(*GetListEntityResponse)(nil),  // 25: keeper.GetListEntityResponse
	(*DeleteEntityRequest)(nil),    // 26: keeper.DeleteEntityRequest
	(*DeleteEntityResponse)(nil),   // 27: keeper.DeleteEntityResponse
	(*UpdateEntityRequest)(nil),    // 28: keeper.UpdateEntityRequest
	(*UpdateEntityResponse)(nil),   // 29: keeper.UpdateEntityResponse
	(*timestamppb.Timestamp)(nil),  // 30: google.protobuf.Timestamp
}
var file_internal_proto_gophkeeper_proto_depIdxs = []int32{
	30, // 0: keeper.Token.iat:type_name -> google.protobuf.Timestamp
	30, // 1: keeper.Token.exp:type_name -> google.protobuf.Timestamp
	30, // 2: keeper.User.createdAt:type_name -> google.protobuf.Timestamp
	30, // 3: keeper.User.updatedAt:type_name -> google.protobuf.Timestamp
	2,  // 4: keeper.AuthenticationResponse.accessToken:type_name -> keeper.Token
	2,  // 5: keeper.RegistrationResponse.accessToken:type_name -> keeper.Token
	30, // 6: keeper.Binary.createdAt:type_name -> google.protobuf.Timestamp
	2,  // 7: keeper.UploadBinaryRequest.accessToken:type_name -> keeper.Token
	2,  // 8: keeper.GetNodeBinaryRequest.accessToken:type_name -> keeper.Token
	10, // 9: keeper.GetNodeBinaryResponse.data:type_name -> keeper.Binary
	2,  // 10: keeper.GetListBinaryRequest.accessToken:type_name -> keeper.Token
	10, // 11: keeper.GetListBinaryResponse.node:type_name -> keeper.Binary
	2,  // 12: keeper.DeleteBinaryRequest.accessToken:type_name -> keeper.Token
	2,  // 13: keeper.DownloadBinaryRequest.accessToken:type_name -> keeper.Token
	30, // 14: keeper.Entity.createdAt:type_name -> google.protobuf.Timestamp
	30, // 15: keeper.Entity.updatedAt:type_name -> google.protobuf.Timestamp
	2,  // 16: keeper.CreateEntityRequest.accessToken:type_name -> keeper.Token
	2,  // 17: keeper.GetListEntityRequest.accessToken:type_name -> keeper.Token
	21, // 18: keeper.GetListEntityResponse.node:type_name -> keeper.Entity
	2,  // 19: keeper.DeleteEntityRequest.accessToken:type_name -> keeper.Token
	2,  // 20: keeper.UpdateEntityRequest.accessToken:type_name -> keeper.Token
	0,  // 21: keeper.GophKeeper.Ping:input_type -> keeper.PingRequest
	8,  // 22: keeper.GophKeeper.UserExist:input_type -> keeper.UserExistRequest
	4,  // 23: keeper.GophKeeper.Authentication:input_type -> keeper.AuthenticationRequest
	6,  // 24: keeper.GophKeeper.Registration:input_type -> keeper.RegistrationRequest
	11, // 25: keeper.GophKeeper.FileUpload:input_type -> keeper.UploadBinaryRequest
	15, // 26: keeper.GophKeeper.FileGetList:input_type -> keeper.GetListBinaryRequest
	17, // 27: keeper.GophKeeper.FileRemove:input_type -> keeper.DeleteBinaryRequest
	19, // 28: keeper.GophKeeper.FileDownload:input_type -> keeper.DownloadBinaryRequest
	22, // 29: keeper.GophKeeper.EntityCreate:input_type -> keeper.CreateEntityRequest
	24, // 30: keeper.GophKeeper.EntityGetList:input_type -> keeper.GetListEntityRequest
	26, // 31: keeper.GophKeeper.EntityDelete:input_type -> keeper.DeleteEntityRequest
	28, // 32: keeper.GophKeeper.EntityUpdate:input_type -> keeper.UpdateEntityRequest
	1,  // 33: keeper.GophKeeper.Ping:output_type -> keeper.PingResponse
	9,  // 34: keeper.GophKeeper.UserExist:output_type -> keeper.UserExistResponse
	5,  // 35: keeper.GophKeeper.Authentication:output_type -> keeper.AuthenticationResponse
	7,  // 36: keeper.GophKeeper.Registration:output_type -> keeper.RegistrationResponse
	12, // 37: keeper.GophKeeper.FileUpload:output_type -> keeper.UploadBinaryResponse
	16, // 38: keeper.GophKeeper.FileGetList:output_type -> keeper.GetListBinaryResponse
	18, // 39: keeper.GophKeeper.FileRemove:output_type -> keeper.DeleteBinaryResponse
	20, // 40: keeper.GophKeeper.FileDownload:output_type -> keeper.DownloadBinaryResponse
	23, // 41: keeper.GophKeeper.EntityCreate:output_type -> keeper.CreateEntityResponse
	25, // 42: keeper.GophKeeper.EntityGetList:output_type -> keeper.GetListEntityResponse
	27, // 43: keeper.GophKeeper.EntityDelete:output_type -> keeper.DeleteEntityResponse
	29, // 44: keeper.GophKeeper.EntityUpdate:output_type -> keeper.UpdateEntityResponse
	33, // [33:45] is the sub-list for method output_type
	21, // [21:33] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_internal_proto_gophkeeper_proto_init() }
func file_internal_proto_gophkeeper_proto_init() {
	if File_internal_proto_gophkeeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_gophkeeper_proto_rawDesc), len(file_internal_proto_gophkeeper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_gophkeeper_proto_goTypes,
		DependencyIndexes: file_internal_proto_gophkeeper_proto_depIdxs,
		MessageInfos:      file_internal_proto_gophkeeper_proto_msgTypes,
	}.Build()
	File_internal_proto_gophkeeper_proto = out.File
	file_internal_proto_gophkeeper_proto_goTypes = nil
	file_internal_proto_gophkeeper_proto_depIdxs = nil
}
