// Code generated by MockGen. DO NOT EDIT.
// Source: internal/tui/types.go

// Package tui is a generated GoMock package.
package tui

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/serg1732/practicum-second-coursework/internal/models"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockClient) Create(ctx context.Context, draft Draft) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, draft)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockClientMockRecorder) Create(ctx, draft interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockClient)(nil).Create), ctx, draft)
}

// Delete mocks base method.
func (m *MockClient) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockClientMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockClient)(nil).Delete), ctx, id)
}

// DeleteLocalFile mocks base method.
func (m *MockClient) DeleteLocalFile(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLocalFile", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLocalFile indicates an expected call of DeleteLocalFile.
func (mr *MockClientMockRecorder) DeleteLocalFile(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLocalFile", reflect.TypeOf((*MockClient)(nil).DeleteLocalFile), ctx, name)
}

// DownloadFile mocks base method.
func (m *MockClient) DownloadFile(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadFile", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DownloadFile indicates an expected call of DownloadFile.
func (mr *MockClientMockRecorder) DownloadFile(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadFile", reflect.TypeOf((*MockClient)(nil).DownloadFile), ctx, name)
}

// Login mocks base method.
func (m *MockClient) Login(ctx context.Context, username, masterPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, username, masterPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// Login indicates an expected call of Login.
func (mr *MockClientMockRecorder) Login(ctx, username, masterPassword interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockClient)(nil).Login), ctx, username, masterPassword)
}

// Logout mocks base method.
func (m *MockClient) Logout(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockClientMockRecorder) Logout(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockClient)(nil).Logout), ctx)
}

// Register mocks base method.
func (m *MockClient) Register(ctx context.Context, username, masterPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, username, masterPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockClientMockRecorder) Register(ctx, username, masterPassword interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockClient)(nil).Register), ctx, username, masterPassword)
}

// RemoveFile mocks base method.
func (m *MockClient) RemoveFile(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFile", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFile indicates an expected call of RemoveFile.
func (mr *MockClientMockRecorder) RemoveFile(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFile", reflect.TypeOf((*MockClient)(nil).RemoveFile), ctx, name)
}

// Sync mocks base method.
func (m *MockClient) Sync(ctx context.Context) (SyncSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync", ctx)
	ret0, _ := ret[0].(SyncSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sync indicates an expected call of Sync.
func (mr *MockClientMockRecorder) Sync(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockClient)(nil).Sync), ctx)
}

// SyncFiles mocks base method.
func (m *MockClient) SyncFiles(ctx context.Context) (SyncSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncFiles", ctx)
	ret0, _ := ret[0].(SyncSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SyncFiles indicates an expected call of SyncFiles.
func (mr *MockClientMockRecorder) SyncFiles(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncFiles", reflect.TypeOf((*MockClient)(nil).SyncFiles), ctx)
}

// Update mocks base method.
func (m *MockClient) Update(ctx context.Context, id string, draft Draft) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, draft)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockClientMockRecorder) Update(ctx, id, draft interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockClient)(nil).Update), ctx, id, draft)
}

// UploadFile mocks base method.
func (m *MockClient) UploadFile(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockClientMockRecorder) UploadFile(ctx, path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockClient)(nil).UploadFile), ctx, path)
}

// MockGophKeeperGRPCClient is a mock of GophKeeperGRPCClient interface.
type MockGophKeeperGRPCClient struct {
	ctrl     *gomock.Controller
	recorder *MockGophKeeperGRPCClientMockRecorder
}

// MockGophKeeperGRPCClientMockRecorder is the mock recorder for MockGophKeeperGRPCClient.
type MockGophKeeperGRPCClientMockRecorder struct {
	mock *MockGophKeeperGRPCClient
}

// NewMockGophKeeperGRPCClient creates a new mock instance.
func NewMockGophKeeperGRPCClient(ctrl *gomock.Controller) *MockGophKeeperGRPCClient {
	mock := &MockGophKeeperGRPCClient{ctrl: ctrl}
	mock.recorder = &MockGophKeeperGRPCClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGophKeeperGRPCClient) EXPECT() *MockGophKeeperGRPCClientMockRecorder {
	return m.recorder
}

// Authentication mocks base method.
func (m *MockGophKeeperGRPCClient) Authentication(ctx context.Context, username, password string) (models.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authentication", ctx, username, password)
	ret0, _ := ret[0].(models.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authentication indicates an expected call of Authentication.
func (mr *MockGophKeeperGRPCClientMockRecorder) Authentication(ctx, username, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authentication", reflect.TypeOf((*MockGophKeeperGRPCClient)(nil).Authentication), ctx, username, password)
}

// CardCreate mocks base method.
func (m *MockGophKeeperGRPCClient) CardCreate(ctx context.Context, name, description, password, paymentSystem, number, holder, cvc, endDate string, token models.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CardCreate", ctx, name, description, password, paymentSystem, number, holder, cvc, endDate, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// CardCreate indicates an expected call of CardCreate.
func (mr *MockGophKeeperGRPCClientMockRecorder) CardCreate(ctx, name, description, password, paymentSystem, number, holder, cvc, endDate, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CardCreate", reflect.TypeOf((*MockGophKeeperGRPCClient)(nil).CardCreate), ctx, name, description, password, paymentSystem, number, holder, cvc, endDate, token)
}

// CardDelete mocks base method.
func (m *MockGophKeeperGRPCClient) CardDelete(ctx context.Context, card string, token models.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CardDelete", ctx, card, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// CardDelete indicates an expected call of CardDelete.
func (mr *MockGophKeeperGRPCClientMockRecorder) CardDelete(ctx, card, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CardDelete", reflect.TypeOf((*MockGophKeeperGRPCClient)(nil).CardDelete), ctx, card, token)
}

// CardUpdate mocks base method.
func (m *MockGophKeeperGRPCClient) CardUpdate(ctx context.Context, name, passwordSecure, paymentSystem, number, holder, cvc, endDateCard string, token models.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CardUpdate", ctx, name, passwordSecure, paymentSystem, number, holder, cvc, endDateCard, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// CardUpdate indicates an expected call of CardUpdate.
func (mr *MockGophKeeperGRPCClientMockRecorder) CardUpdate(ctx, name, passwordSecure, paymentSystem, number, holder, cvc, endDateCard, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CardUpdate", reflect.TypeOf((*MockGophKeeperGRPCClient)(nil).CardUpdate), ctx, name, passwordSecure, paymentSystem, number, holder, cvc, endDateCard, token)
}

// CredsCreate mocks base method.
func (m *MockGophKeeperGRPCClient) CredsCreate(ctx context.Context, name, description, passwordSecure, login, password string, token models.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CredsCreate", ctx, name, description, passwordSecure, login, password, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// CredsCreate indicates an expected call of CredsCreate.
func (mr *MockGophKeeperGRPCClientMockRecorder) CredsCreate(ctx, name, description, passwordSecure, login, password, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CredsCreate", reflect.TypeOf((*MockGophKeeperGRPCClient)(nil).CredsCreate), ctx, name, description, passwordSecure, login, password, token)
}

// CredsDelete mocks base method.
func (m *MockGophKeeperGRPCClient) CredsDelete(ctx context.Context, creds string, token models.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CredsDelete", ctx, creds, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// CredsDelete indicates an expected call of CredsDelete.
func (mr *MockGophKeeperGRPCClientMockRecorder) CredsDelete(ctx, creds, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CredsDelete", reflect.TypeOf((*MockGophKeeperGRPCClient)(nil).CredsDelete), ctx, creds, token)
}

// CredsUpdate mocks base method.
func (m *MockGophKeeperGRPCClient) CredsUpdate(ctx context.Context, name, passwordSecure, login, password string, token models.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CredsUpdate", ctx, name, passwordSecure, login, password, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// CredsUpdate indicates an expected call of CredsUpdate.
func (mr *MockGophKeeperGRPCClientMockRecorder) CredsUpdate(ctx, name, passwordSecure, login, password, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CredsUpdate", reflect.TypeOf((*MockGophKeeperGRPCClient)(nil).CredsUpdate), ctx, name, passwordSecure, login, password, token)
}

// FileDownload mocks base method.
func (m *MockGophKeeperGRPCClient) FileDownload(ctx context.Context, name, password string, token models.Token) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileDownload", ctx, name, password, token)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FileDownload indicates an expected call of FileDownload.
func (mr *MockGophKeeperGRPCClientMockRecorder) FileDownload(ctx, name, password, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileDownload", reflect.TypeOf((*MockGophKeeperGRPCClient)(nil).FileDownload), ctx, name, password, token)
}

// FileRemove mocks base method.
func (m *MockGophKeeperGRPCClient) FileRemove(ctx context.Context, binary string, token models.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileRemove", ctx, binary, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// FileRemove indicates an expected call of FileRemove.
func (mr *MockGophKeeperGRPCClientMockRecorder) FileRemove(ctx, binary, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileRemove", reflect.TypeOf((*MockGophKeeperGRPCClient)(nil).FileRemove), ctx, binary, token)
}

// FileUpload mocks base method.
func (m *MockGophKeeperGRPCClient) FileUpload(ctx context.Context, name, password string, file []byte, token models.Token) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileUpload", ctx, name, password, file, token)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FileUpload indicates an expected call of FileUpload.
func (mr *MockGophKeeperGRPCClientMockRecorder) FileUpload(ctx, name, password, file, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileUpload", reflect.TypeOf((*MockGophKeeperGRPCClient)(nil).FileUpload), ctx, name, password, file, token)
}

// Registration mocks base method.
func (m *MockGophKeeperGRPCClient) Registration(ctx context.Context, username, password string) (models.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Registration", ctx, username, password)
	ret0, _ := ret[0].(models.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Registration indicates an expected call of Registration.
func (mr *MockGophKeeperGRPCClientMockRecorder) Registration(ctx, username, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Registration", reflect.TypeOf((*MockGophKeeperGRPCClient)(nil).Registration), ctx, username, password)
}

// Synchronize mocks base method.
func (m *MockGophKeeperGRPCClient) Synchronize(ctx context.Context, password string, token models.Token) (models.SyncResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Synchronize", ctx, password, token)
	ret0, _ := ret[0].(models.SyncResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Synchronize indicates an expected call of Synchronize.
func (mr *MockGophKeeperGRPCClientMockRecorder) Synchronize(ctx, password, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Synchronize", reflect.TypeOf((*MockGophKeeperGRPCClient)(nil).Synchronize), ctx, password, token)
}

// TextCreate mocks base method.
func (m *MockGophKeeperGRPCClient) TextCreate(ctx context.Context, name, description, password, plaintext string, token models.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TextCreate", ctx, name, description, password, plaintext, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// TextCreate indicates an expected call of TextCreate.
func (mr *MockGophKeeperGRPCClientMockRecorder) TextCreate(ctx, name, description, password, plaintext, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TextCreate", reflect.TypeOf((*MockGophKeeperGRPCClient)(nil).TextCreate), ctx, name, description, password, plaintext, token)
}

// TextDelete mocks base method.
func (m *MockGophKeeperGRPCClient) TextDelete(ctx context.Context, text string, token models.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TextDelete", ctx, text, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// TextDelete indicates an expected call of TextDelete.
func (mr *MockGophKeeperGRPCClientMockRecorder) TextDelete(ctx, text, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TextDelete", reflect.TypeOf((*MockGophKeeperGRPCClient)(nil).TextDelete), ctx, text, token)
}

// TextUpdate mocks base method.
func (m *MockGophKeeperGRPCClient) TextUpdate(ctx context.Context, name, passwordSecure, text string, token models.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TextUpdate", ctx, name, passwordSecure, text, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// TextUpdate indicates an expected call of TextUpdate.
func (mr *MockGophKeeperGRPCClientMockRecorder) TextUpdate(ctx, name, passwordSecure, text, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TextUpdate", reflect.TypeOf((*MockGophKeeperGRPCClient)(nil).TextUpdate), ctx, name, passwordSecure, text, token)
}
